Implement basic functionality

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,31 @@ jobs:
       - name: Scan for common Rails security vulnerabilities using static analysis
         run: bin/brakeman --no-pager
 
+  bundle-audit:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: .ruby-version
+          bundler-cache: true
+
+      - name: Install dependencies
+        run: bundle install
+
+      - name: Run bundle-audit check
+        run: bundle exec bundle-audit check --update
+
+      - name: Fail if vulnerabilities are found
+        run: |
+          if bundle exec bundle-audit check --update | grep -q "Vulnerabilities found"; then
+            echo "Vulnerabilities found! Failing the job.";
+            exit 1;
+          fi
+
   lint:
     runs-on: ubuntu-latest
     steps:
